Rework what frontend does with revocation
revocation.sh cron job:
- frontend now collects all the CRLs and local entries and combines them in a
  tarball for the backend. The backend can then figure out what to do with the
  next CRL number and whether a new CRL needs to be made since it has more
  access to its own CA files.
- it still needs to figure out what is the best CRL to publish.
- entries files are cached since openssl crl is expensive
- when no CRLs or entries files have changed we don't need to do anything.

revoke_cert.sh.j2:
- should be bash script
- update parsing args

update defaults values and config/PLACEHOLDER for delegserver role

diff --git a/roles/delegserver/templates/revoke_cert.sh.j2 b/roles/delegserver/templates/revoke_cert.sh.j2
--- a/roles/delegserver/templates/revoke_cert.sh.j2
+++ b/roles/delegserver/templates/revoke_cert.sh.j2
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # Default variables
 revokequeuedir={{ revoke_queue_dir }}
@@ -22,21 +22,23 @@ cd $revokequeuedir
 # Add new revokes when applicable
 for arg in $*;do
     # Check it is a valid number
+    arg=${arg#0x}
     if [ "$(echo "$arg"|sed 's/[^0-9a-fA-F]\+//')" != "$arg" ];then
-	echo "Warning: skipping invalid hexadecimal number $arg" >&2
-	continue
+        echo "Warning: skipping invalid hexadecimal number $arg" >&2
+        continue
     fi
 
     # Prefix with 0x when needed
-    if echo "$arg" | grep -ivq "^0x";then
-	arg=0x$arg
-    fi
+    arg=0x${arg#0x}
+
     # Format the serial to be of the right OpenSSL length
     serial=$(printf "%0$(((1+$(printf "%X" $arg|wc -c))/2*2))X" $arg)
-    if [ -f $serial ];then
-	echo "Skipping already present serial $serial"
+    if [ -f "$serial" ];then
+        printf "Skipping already present serial 0x%s (=%d)\n" \
+            "$serial" "0x${serial}"
     else
-	echo "Adding serial $serial"
-	touch $serial
+        printf "Adding serial 0x%s (=%d)\n" \
+            "$serial" "0x${serial}"
+        touch "$serial"
     fi
 done
