Big overhaul mostly related to revocation:
- add/change various new variables mostly for the new revocation.sh cronjob.
  This new cronjob replaces the very simple old crl_publish.sh cronjob. It takes
  input from it's backend and zero or more delegation servers' CRLs to get to
  the best set and serial number:
    - We already allow for multiple backends in the revocation.sh, although this
      branch only uses a single one.
    - change backup directory (in common role) to be under private_ca_fqdn for
      the same reason.
    - the revocation.sh cronjob uses also input via curl from different remote
      delegation servers to make sure the CRL serial remain monotoneously
      increasing and to get all to-be-revoked certificates in HA setups.
- revoke_cert.sh script now just touches files in a new revoke_queue_dir, these
  are picked up by the revocation.sh cronjob to actually be parsed. This
  prevents race conditions etc.
- setting up the revocation.sh script and cronjob is now (only) done in
  revoke-frontend.yml instead of partially in webroot.yml
- we define myproxy_cert/key variable to use in ca_checker to do a
  client-authenticated info request instead of the more simple CA test.
- update the access.conf in ca-sshd.yml and ca-backup.yml instead of
  access.conf.j2. That is easier for sites not running access.yml (such as
  Nikhef). This was already partially the case, now it's more consistent.
- run ca_checker cron when ping fails. This way we can much quicker inform the
  sysadmin without the overhead of that script if everything is fine.
- ca_checker is reworked a bit for more flexibility in acting when the backend
  fails or recovers

diff --git a/roles/delegserver/templates/revoke_cert.sh.j2 b/roles/delegserver/templates/revoke_cert.sh.j2
--- a/roles/delegserver/templates/revoke_cert.sh.j2
+++ b/roles/delegserver/templates/revoke_cert.sh.j2
@@ -1,63 +1,42 @@
 #!/bin/sh
 
 # Default variables
-revokedir={{ revoke_dir }}
-revokewebroot={{ revoke_dir_webroot }}
-revokepfx={{ revoke_pfx }}
-revokelatest=${revokewebroot}/{{ revoke_latest }}
+revokequeuedir={{ revoke_queue_dir }}
 
 # Check command line argument(s)
 if [ $# -lt 1 ];then
     echo "Usage: $(basename $0) <hex serial(s)>" >&2
-    exit 1
+    exit 0
 fi
 
 # Set umask
 umask 0022
 
 # Create revoke directory when needed
-if [ ! -d $revokedir ];then
-    mkdir -p $revokedir
-    echo "Created directory $revokedir"
+if [ ! -d "$revokequeuedir" ];then
+    mkdir -p $revokequeuedir
+    echo "Created directory \"$revokequeuedir\""
 fi
-if [ ! -d $revokewebroot ];then
-    mkdir -p $revokewebroot
-    echo "Created directory $revokewebroot"
-fi
-cd $revokedir
+cd $revokequeuedir
 
-# Create tempfile containing the merge of the previous file and the new to be
-# revoked certificate numbers
-revoketmp=$(mktemp ${revokedir}/${revokepfx}XXXXXX)
-if [ -f "$revokelatest" ];then
-    cat $revokelatest > $revoketmp
-fi
+# Add new revokes when applicable
 for arg in $*;do
-    # Add 0x to arg when needed
+    # Check it is a valid number
+    if [ "$(echo "$arg"|sed 's/[^0-9a-fA-F]\+//')" != "$arg" ];then
+	echo "Warning: skipping invalid hexadecimal number $arg" >&2
+	continue
+    fi
+
+    # Prefix with 0x when needed
     if echo "$arg" | grep -ivq "^0x";then
 	arg=0x$arg
     fi
     # Format the serial to be of the right OpenSSL length
-    printf "%0$(((1+$(printf "%X" $arg|wc -c))/2*2))X" $arg >> $revoketmp
+    serial=$(printf "%0$(((1+$(printf "%X" $arg|wc -c))/2*2))X" $arg)
+    if [ -f $serial ];then
+	echo "Skipping already present serial $serial"
+    else
+	echo "Adding serial $serial"
+	touch $serial
+    fi
 done
-
-# Create sorted new revoke file
-revokenew=${revokedir}/${revokepfx}$(date +%Y%m%d%H%M%S)
-if [ -f "$revokenew" ];then
-    echo "ERROR: new revoke file $revokenew already exists" >&2
-    rm $revoketmp
-    exit 1
-fi
-sort -u $revoketmp > $revokenew
-rm $revoketmp
-
-# Check wether something has changed
-if [ ! -f $revokelatest ] || ! diff $revokenew $revokelatest > /dev/null;then
-    # Make symlink for the new latest file
-    ln -sf $revokenew $revokelatest
-    echo "Symlink $revokelatest updated to point to new revoke list $revokenew"
-else
-    # Nothing changed, tidy up
-    rm $revokenew
-    echo "No new revoke list, $revokelatest still pointing to latest"
-fi
